// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_im_not_a_pirate_im_a_captain = "CgkIxsXUmckXEAIQDg"; // <GPGSID>
        public const string achievement_im_still_alive = "CgkIxsXUmckXEAIQBw"; // <GPGSID>
        public const string achievement_agent_337 = "CgkIxsXUmckXEAIQCw"; // <GPGSID>
        public const string achievement_there_is_no_cow_level = "CgkIxsXUmckXEAIQAw"; // <GPGSID>
        public const string achievement_best_present = "CgkIxsXUmckXEAIQDQ"; // <GPGSID>
        public const string leaderboard_top_ninjas = "CgkIxsXUmckXEAIQAg"; // <GPGSID>
        public const string achievement_story_mode = "CgkIxsXUmckXEAIQCA"; // <GPGSID>
        public const string achievement_epic_hero = "CgkIxsXUmckXEAIQBQ"; // <GPGSID>
        public const string achievement_what_did_the_ranger_forget_in_the_city = "CgkIxsXUmckXEAIQDw"; // <GPGSID>
        public const string achievement_samurai_its_like_ninja_but_samurai = "CgkIxsXUmckXEAIQDA"; // <GPGSID>
        public const string achievement_stairway_to_heaven = "CgkIxsXUmckXEAIQCQ"; // <GPGSID>
        public const string achievement_ultra_mega_high_jump = "CgkIxsXUmckXEAIQBg"; // <GPGSID>
        public const string achievement_ghostbuster = "CgkIxsXUmckXEAIQBA"; // <GPGSID>

}

